spring:
  application:
    name: nacos-provider-2
  main:
    allow-bean-definition-overriding: true
demo:
  service:
    version: 1.0.1
    group: nacos


dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8847
server:
  port: 9002