spring:
  application:
    name: spring-cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    loadbalancer:
      retry:
        enabled: false

server:
  port: 18035


management:
  server:
    port: 32002
    base-path: "/"
