spring:
  application:
    name: nacos-consumer
  main:
    allow-bean-definition-overriding: true

demo:
  service:
    version: 1.0.0
    group: zk
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
server:
  port: 18080