spring:
  application:
    name: nacos-provider-cloud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: false
server:
  port: 18088
